export const PENIS_ANIMALS = [
  {
    id: "echidna",
    name: "Echidna",
    emoji: "🦔",
    count: 4,
    fact: "The echidna has a 4-headed penis — but only 2 heads activate at a time!",
  },
  {
    id: "snake",
    name: "King Cobra",
    emoji: "🐍",
    count: 2,
    fact: "All snakes have 2 penises (hemipenes) and alternate which one they use!",
  },
  {
    id: "shark",
    name: "Great White Shark",
    emoji: "🦈",
    count: 2,
    fact: "Sharks have 2 claspers — one on each side of their body near the tail.",
  },
  {
    id: "kangaroo",
    name: "Kangaroo",
    emoji: "🦘",
    count: 2,
    fact: "Male kangaroos have 2 penises to match the female's 2 lateral vaginas!",
  },
  {
    id: "koala",
    name: "Koala",
    emoji: "🐨",
    count: 2,
    fact: "The koala's penis is bifurcated — split into two tips — to fit the female's dual vaginas.",
  },
  {
    id: "lizard",
    name: "Blue-Tongued Lizard",
    emoji: "🦎",
    count: 2,
    fact: "All lizards have 2 hemipenes, often covered in spines to grip during mating!",
  },
  {
    id: "spider",
    name: "Orb-Weaver Spider",
    emoji: "🕷️",
    count: 2,
    fact: "Male spiders have 2 pedipalps used as penises — and often lose them after mating.",
  },
  {
    id: "millipede",
    name: "Giant Millipede",
    emoji: "🐛",
    count: 2,
    fact: "Millipedes have 2 gonopods on their 7th body segment used for reproduction.",
  },
  {
    id: "dragonfly",
    name: "Dragonfly",
    emoji: "🪲",
    count: 2,
    fact: "Dragonflies have a primary and secondary penis — they transfer sperm between them before mating!",
  },
  {
    id: "human",
    name: "Human",
    emoji: "🧑",
    count: 1,
    fact: "Humans are pretty standard with just the one. Boring but functional!",
  },
  {
    id: "lion",
    name: "Lion",
    emoji: "🦁",
    count: 1,
    fact: "A lion can mate up to 50 times a day during peak season. Quality vs quantity.",
  },
  {
    id: "whale",
    name: "Blue Whale",
    emoji: "🐋",
    count: 1,
    fact: "The blue whale has the largest penis of any animal — up to 3 metres long!",
  },
  {
    id: "elephant",
    name: "African Elephant",
    emoji: "🐘",
    count: 1,
    fact: "An elephant's penis is prehensile — it can move it like a fifth limb.",
  },
  {
    id: "duck",
    name: "Mallard Duck",
    emoji: "🦆",
    count: 1,
    fact: "A duck's penis is corkscrew-shaped and can be longer than its entire body!",
  },
  {
    id: "barnacle",
    name: "Barnacle",
    emoji: "🐚",
    count: 1,
    fact: "Barnacles have the longest penis relative to body size of any animal — up to 50x their body length!",
  },
  {
    id: "pig",
    name: "Pig",
    emoji: "🐷",
    count: 1,
    fact: "A pig's penis is also corkscrew-shaped — convergent evolution with the duck!",
  },
  {
    id: "dolphin",
    name: "Bottlenose Dolphin",
    emoji: "🐬",
    count: 1,
    fact: "Dolphin penises are prehensile — they can rotate nearly 360 degrees!",
  },
  {
    id: "cat",
    name: "Domestic Cat",
    emoji: "🐱",
    count: 1,
    fact: "A cat's penis is covered in backward-pointing spines to stimulate ovulation in the female.",
  },
  {
    id: "horse",
    name: "Horse",
    emoji: "🐴",
    count: 1,
    fact: "Stallions have a retractable penis that stays hidden when not in use.",
  },
  {
    id: "gorilla",
    name: "Gorilla",
    emoji: "🦍",
    count: 1,
    fact: "Despite their massive size, gorillas have the smallest penis of all great apes.",
  },
  {
    id: "rhino",
    name: "White Rhinoceros",
    emoji: "🦏",
    count: 1,
    fact: "A rhino's penis points backwards — so it urinates backwards too!",
  },
  {
    id: "turtle",
    name: "Sea Turtle",
    emoji: "🐢",
    count: 1,
    fact: "A sea turtle's penis can be over 30cm long and is a dark purple colour.",
  },
  {
    id: "bonobo",
    name: "Bonobo",
    emoji: "🐒",
    count: 1,
    fact: "Bonobos use sex to resolve conflicts — they're the hippies of the primate world.",
  },
  {
    id: "chimpanzee",
    name: "Chimpanzee",
    emoji: "🐵",
    count: 1,
    fact: "Chimps have a baculum (penis bone) — something humans lost through evolution.",
  },
  {
    id: "bedbug",
    name: "Bed Bug",
    emoji: "🪳",
    count: 1,
    fact: "Bed bugs practice 'traumatic insemination' — the male stabs the female anywhere on her body.",
  },
  {
    id: "argonaut",
    name: "Argonaut Octopus",
    emoji: "🐙",
    count: 1,
    fact: "The male argonaut's reproductive arm detaches and swims to the female on its own — the male dies after!",
  },
  {
    id: "frog",
    name: "Common Frog",
    emoji: "🐸",
    count: 0,
    fact: "Most frogs have NO penis at all — they fertilise eggs externally in the water!",
  },
  {
    id: "platypus_m",
    name: "Platypus",
    emoji: "🦆",
    count: 0,
    fact: "The platypus has no penis — it reproduces through a cloaca like birds. Weird even for a weird animal!",
  },
  {
    id: "salmon",
    name: "Atlantic Salmon",
    emoji: "🐟",
    count: 0,
    fact: "Salmon have no penis — males release sperm directly into the water over the eggs!",
  },
  {
    id: "rooster",
    name: "Rooster",
    emoji: "🐓",
    count: 0,
    fact: "Most birds including roosters have no penis — they reproduce via a 'cloacal kiss'!",
  },
];

export const VAGINA_ANIMALS = [
  {
    id: "kangaroo_f",
    name: "Kangaroo",
    emoji: "🦘",
    count: 3,
    fact: "Female kangaroos have 3 vaginas — 2 for sperm, 1 as the birth canal. She can be pregnant in all simultaneously!",
  },
  {
    id: "koala_f",
    name: "Koala",
    emoji: "🐨",
    count: 3,
    fact: "Koalas share the marsupial triple-vagina system — the central one opens permanently after the first birth!",
  },
  {
    id: "wombat",
    name: "Wombat",
    emoji: "🐻",
    count: 3,
    fact: "Wombats have 3 vaginas AND produce cube-shaped poop. Nature was going through something.",
  },
  {
    id: "tasmanian_devil",
    name: "Tasmanian Devil",
    emoji: "😈",
    count: 3,
    fact: "Tasmanian devils have 3 vaginas and give birth to up to 50 joeys — but only 4 nipples exist in the pouch!",
  },
  {
    id: "snake_f",
    name: "Boa Constrictor",
    emoji: "🐍",
    count: 2,
    fact: "Female snakes have 2 hemiclitorises — the paired female equivalent of hemipenes!",
  },
  {
    id: "spider_f",
    name: "Black Widow Spider",
    emoji: "🕷️",
    count: 2,
    fact: "Female spiders have 2 separate genital openings — one for each of the male's pedipalps.",
  },
  {
    id: "human_f",
    name: "Human",
    emoji: "👩",
    count: 1,
    fact: "Humans are placental mammals — one uterus, one vagina. Simple but effective!",
  },
  {
    id: "elephant_f",
    name: "African Elephant",
    emoji: "🐘",
    count: 1,
    fact: "The elephant's vagina is located on her underside, not her rear — making elephant sex quite acrobatic.",
  },
  {
    id: "shark_f",
    name: "Great White Shark",
    emoji: "🦈",
    count: 1,
    fact: "Female sharks are often bitten by males during mating — their skin is 3x thicker as a result!",
  },
  {
    id: "dolphin_f",
    name: "Bottlenose Dolphin",
    emoji: "🐬",
    count: 1,
    fact: "Dolphin vaginas have internal folds that act like a maze — giving the female cryptic control over fertilisation.",
  },
  {
    id: "duck_f",
    name: "Mallard Duck",
    emoji: "🦆",
    count: 1,
    fact: "Female duck vaginas are counter-corkscrew shaped — a biological arms race against the male's corkscrew penis!",
  },
  {
    id: "platypus_f",
    name: "Platypus",
    emoji: "🦆",
    count: 1,
    fact: "Platypuses lay eggs but do have a vagina — they're confusing even by mammal standards.",
  },
  {
    id: "lioness",
    name: "Lioness",
    emoji: "🦁",
    count: 1,
    fact: "Lionesses are induced ovulators — the barbed male penis causes ovulation to trigger. Ouch.",
  },
  {
    id: "mare",
    name: "Mare (Horse)",
    emoji: "🐴",
    count: 1,
    fact: "Mares have a remarkably efficient reproductive tract — sperm can travel it in under 4 hours.",
  },
  {
    id: "gorilla_f",
    name: "Gorilla",
    emoji: "🦍",
    count: 1,
    fact: "Female gorillas are highly selective — they choose who they mate with despite living in a harem structure.",
  },
  {
    id: "cat_f",
    name: "Domestic Cat",
    emoji: "🐱",
    count: 1,
    fact: "Like the lioness, female cats are induced ovulators — mating itself triggers the release of eggs.",
  },
  {
    id: "cow",
    name: "Cow",
    emoji: "🐄",
    count: 1,
    fact: "A cow's reproductive cycle is so reliable it's been used as a model for human fertility research.",
  },
  {
    id: "bonobo_f",
    name: "Bonobo",
    emoji: "🐒",
    count: 1,
    fact: "Female bonobos are dominant in their society and use sex as a social bonding tool, not just reproduction.",
  },
  {
    id: "komodo",
    name: "Komodo Dragon",
    emoji: "🦎",
    count: 1,
    fact: "Female Komodo dragons can reproduce without a male through parthenogenesis — virgin birth!",
  },
  {
    id: "octopus_f",
    name: "Octopus",
    emoji: "🐙",
    count: 1,
    fact: "The female octopus accepts the male's detached reproductive arm and stores the sperm for later.",
  },
  {
    id: "clownfish",
    name: "Clownfish",
    emoji: "🐠",
    count: 1,
    fact: "All clownfish are born male — the dominant one changes sex to female. Nemo's dad would become his mum!",
  },
  {
    id: "seahorse_f",
    name: "Seahorse",
    emoji: "🐡",
    count: 1,
    fact: "Female seahorses deposit eggs into the MALE's pouch — he carries and gives birth to the young!",
  },
  {
    id: "queen_bee",
    name: "Queen Bee",
    emoji: "🐝",
    count: 1,
    fact: "A queen bee mates once in her life with up to 15 drones, storing enough sperm to last 5 years!",
  },
  {
    id: "axolotl",
    name: "Axolotl",
    emoji: "🦎",
    count: 1,
    fact: "Axolotls never fully grow up — they're permanently juvenile (neotenic). Even their reproduction is weird.",
  },
  {
    id: "hen",
    name: "Hen (Chicken)",
    emoji: "🐔",
    count: 1,
    fact: "Hens can store sperm from multiple males and choose which sperm fertilises each egg!",
  },
  {
    id: "whale_f",
    name: "Blue Whale",
    emoji: "🐋",
    count: 1,
    fact: "A blue whale vagina can be over 2 metres long. The baby at birth is already 7 metres long!",
  },
  {
    id: "rhino_f",
    name: "White Rhinoceros",
    emoji: "🦏",
    count: 1,
    fact: "Female rhinos have an 18-month gestation period — one of the longest of any land mammal.",
  },
  {
    id: "hyena",
    name: "Spotted Hyena",
    emoji: "🐾",
    count: 0,
    fact: "Female spotted hyenas have NO external vaginal opening — they have a pseudo-penis instead! Birth looks terrifying.",
  },
  {
    id: "bedbug_f",
    name: "Bed Bug",
    emoji: "🪳",
    count: 0,
    fact: "Female bed bugs have no vagina at all — the male stabs through her abdomen to deliver sperm directly!",
  },
  {
    id: "salmon_f",
    name: "Atlantic Salmon",
    emoji: "🐟",
    count: 0,
    fact: "Female salmon release eggs directly into the water — no internal fertilisation, so no vagina needed!",
  },
];
